xen: Fix QA Issue with pygrub
Yocto complains:

ERROR: xen-tools-4.15.0+gitAUTOINC+adeb27e304-r0 do_package_qa: QA Issue: xen-tools-pygrub:
... pygrub maximum shebang size exceeded, the maximum size is 128. [shebang-size]

Actually, we don't need the pygrub to be installed since we don't use
its functionally at all. So remove it for now.

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
Signed-off-by: Valerii Chubar <valerii_chubar@epam.com>